# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'ordering': ['-create_date'],
                'get_latest_by': 'create_date',
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
